apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ib-sriov-network
  annotations:
    k8s.v1.cni.cncf.io/resourceName: mellanox.com/mlnx_sriov_rdma_vf
spec:
  config: '{
  "type": "ib-sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "link_state": "enable",
  "ibKubernetesEnabled": false,
  "rdmaIsolation": true,
  "deviceID": "0000:08:00.1",
  "ipam": {
    "type": "host-local",
    "subnet": "10.1.34.0/24"
  }
}'